### PR TITLE
check the pull request rule

### PR DESCRIPTION
**Pull request by GimhaniKaushalya**
please check this one

### CODE REVIEW

**Review by akilamadhufin — APPROVED** [review]
This code works fine. Approved.

**Review by Jayaneththi — APPROVED** [review]
color sensor java codes are reviewed . no need more changes.

**Review by Yashodha8890 — APPROVED** [review]
Code seems fine. Approving the pull request.

**Comment by GimhaniKaushalya** [comment]
color sensor is work fine.

**Pull request merged**
